name: Build images

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      default_branch: ${{ steps.ctx.outputs.default_branch }}
      matrix:         ${{ steps.mk.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: ctx
        run: echo "default_branch=${{ github.event.repository.default_branch || 'main' }}" >> "$GITHUB_OUTPUT"

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - id: mk
        run: |
          matrix=$(python .github/scripts/discover_images.py)
          echo "matrix=${matrix}" >> "$GITHUB_OUTPUT"

  build_all:
    name: Build images
    needs: discover
    if: ${{ needs.discover.outputs.matrix != '' && needs.discover.outputs.matrix != '{"include":[]}' }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix: ${{ fromJson(needs.discover.outputs.matrix) }}
    uses: ./.github/workflows/_build-image.yml
    with:
      dir:            ${{ matrix.dir }}
      name:           ${{ matrix.name }}
      platforms:      ${{ matrix.platforms }}
      rebuild_policy: ${{ matrix.rebuild_policy }}
      hidden:         ${{ matrix.hidden }}
      default_branch: ${{ needs.discover.outputs.default_branch }}
    secrets: inherit
